// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Gola wala",
  category: "Ice cream shop",
  address: "\nGF-08, Atlantis one, opp. Hirashs arcade, nr. SAGAR SANGEET COMPLEX, Science City, Sola, Ahmedabad, Gujarat 380060",
  phone: "",
  email: "",
  website: "http://www.golawala.in/",
  mapUrl: "https://www.google.com/maps/place/Gola+wala/@23.0769843,72.518777,17z/data=!3m1!4b1!4m6!3m5!1s0x395e9d00319b07c9:0x39a301934cb8942f!8m2!3d23.0769843!4d72.518777!16s%2Fg%2F11ypr7ghnt?entry=ttu&g_ep=EgoyMDI2MDUyNS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0769843",
  longitude: "72.518777",
  rating: "",
  reviewsCount: "64",
  openingHours: "Show open hours for the week",
  logo: "/images/logo.png",
  images: ["/images/gmap_1779969217342_0.jpg", "/images/gmap_1779969217384_1.jpg", "/images/gmap_1779969217427_2.jpg", "/images/gmap_1779969217451_3.jpg", "/images/gmap_1779969217479_4.jpg", "/images/gmap_1779969217507_5.jpg", "/images/gmap_1779969217533_6.jpg", "/images/website_0.jpg"],
  description: "",
  socials: {"facebook":"https://www.facebook.com/golawalaofficial","instagram":"https://www.instagram.com/golawala_official/?igsh=Y3Nvc3N0OHA0NGFq","whatsapp":"https://api.whatsapp.com/send/?phone=919824318583&text&type=phone_number&app_absent=0"},
};

export const aiContent = {
  tagline: "Savor Ahmedabad's Flavor",
  heroDescription: "Gola wala is a popular ice cream shop located in the heart of Ahmedabad, Gujarat. We offer a wide range of delicious and unique flavors that are sure to tantalize your taste buds. Visit us today at GF-08, Atlantis one, opp. Hirashs arcade, nr. SAGAR SANGEET COMPLEX, Science City, Sola, Ahmedabad.",
  aboutTitle: "The Story of Gola wala",
  aboutText: "Gola wala is nestled in the vibrant city of Ahmedabad, specifically at  GF-08, Atlantis one, opp. Hirashs arcade, nr. SAGAR SANGEET COMPLEX, Science City, Sola. Our shop is a haven for ice cream lovers, offering an array of mouth-watering flavors that cater to all tastes and preferences. With a commitment to quality and customer satisfaction, we have become a beloved destination in the city.",
  services: [
    { icon: "🍦", title: "Gola wala Specials", description: "Our signature ice cream flavors, made with love and care, to give you a taste of Ahmedabad's authentic flavor" },
    { icon: "🌮", title: "Regional Flavors", description: "Experience the unique taste of Gujarat with our specially crafted regional flavors, inspired by local ingredients and traditions" },
    { icon: "🎂", title: "Customized Ice Cream Cakes", description: "Make your special occasions even sweeter with our customized ice cream cakes, available in a variety of flavors and designs" },
    { icon: "🍫", title: "Gola wala Combos", description: "Indulge in our specially curated combos, featuring a mix of our signature ice cream flavors and other sweet treats" },
    { icon: "🥛", title: "Fresh Fruit Ice Creams", description: "Savor the freshness of seasonal fruits in our unique and refreshing fruit-based ice cream flavors" },
    { icon: "🍦", title: "Gola wala's Special Sundaes", description: "Treat yourself to our decadent sundaes, featuring a rich blend of ice cream, toppings, and sauces" }
  ],
  whyChooseUs: [
    { icon: "💯", title: "Quality Guarantee", description: "We use only the finest ingredients and maintain the highest standards of quality in our products" },
    { icon: "👥", title: "Friendly Service", description: "Our staff is always ready to welcome you with a smile and provide exceptional customer service" },
    { icon: "📍", title: "Convenient Location", description: "Located in the heart of Ahmedabad, our shop is easily accessible and convenient to visit" },
    { icon: "👍", title: "Customer Feedback", description: "We value your feedback and continuously work to improve our products and services based on your suggestions" }
  ],
  testimonials: [
    { name: "Manish Mehta", role: "Regular Customer", text: "I've been visiting Gola wala for years, and their ice cream flavors never fail to impress me. The staff is friendly, and the atmosphere is always lively.", rating: 5 },
    { name: "Mansi Patel", role: "Food Blogger", text: "Gola wala's unique regional flavors are a must-try for anyone visiting Ahmedabad. Their customized ice cream cakes are also a great option for special occasions.", rating: 5 },
    { name: "Mayank Shah", role: "Local Resident", text: "Gola wala is my go-to destination for a quick dessert fix. Their fresh fruit ice creams are refreshing and perfect for hot summer days.", rating: 5 }
  ],
  portfolio: { categories: [{ name: "Ice Cream Flavors", items: [{ title: "Gola wala Special", description: "Our signature ice cream flavor, made with love and care", icon: "🍦" }, { title: "Mango Magic", description: "A sweet and creamy mango-based ice cream flavor", icon: "🥭" }] },
    { name: "Customized Cakes", items: [{ title: "Birthday Cake", description: "A customized ice cream cake for special birthdays", icon: "🎂" }, { title: "Wedding Cake", description: "A unique and delicious ice cream cake for wedding celebrations", icon: "💕" }] },
    { name: "Gola wala Combos", items: [{ title: "Fruit Combo", description: "A mix of our fresh fruit ice creams", icon: "🍉" }, { title: "Sundae Combo", description: "A decadent sundae featuring our signature ice cream flavors", icon: "🍦" }] },
    { name: "Seasonal Offers", items: [{ title: "Summer Special", description: "A refreshing ice cream flavor perfect for hot summer days", icon: "☀️" }, { title: "Winter Delight", description: "A warm and comforting ice cream flavor for the winter season", icon: "❄️" }] }] },
  faq: { items: [{ question: "What are the business hours of Gola wala?", answer: "Gola wala is open from 11am to 11pm, 7 days a week. However, please note that hours may be subject to change during holidays or special events." },
    { question: "Do you offer customized ice cream cakes for special occasions?", answer: "Yes, we offer customized ice cream cakes for birthdays, weddings, and other special occasions. Please contact us in advance to place your order." },
    { question: "Can I place an order for delivery or takeaway?", answer: "Yes, we offer delivery and takeaway services. Please contact us to place your order and we will be happy to assist you." },
    { question: "What are the prices of your ice cream flavors?", answer: "Our ice cream flavors are priced between ₹50 to ₹200, depending on the size and type of ice cream. Please visit our shop or contact us for more information." },
    { question: "Do you have any ongoing promotions or discounts?", answer: "Yes, we regularly offer promotions and discounts on our products. Please follow us on social media or visit our website to stay updated on our latest offers." },
    { question: "How can I contact Gola wala for feedback or inquiries?", answer: "You can contact us through our website, social media, or by visiting our shop in person. We value your feedback and look forward to hearing from you." }] },
  ctaTitle: "Indulge in the Flavor",
  ctaDescription: "Visit us today and treat yourself to a delicious ice cream experience. Our friendly staff will be happy to assist you in choosing the perfect flavor.",
  ctaButtonText: "Get Your Ice Cream",
  metaDescription: "Gola wala: Ahmedabad's favorite ice cream shop",
};

export const siteConfig = {
  layout: "minimal-luxury",
  theme: "warm",
  sections: ["about", "customer", "a", "faq", "skip", "google", "alt", "gallery", "open", "blog", "structured", "contact", "portfolio"],
  heroVariant: "fullscreen-cinematic",
  navStyle: "sticky-blur",
  animationStyle: "blur-in-sharp",
  cardStyle: "rounded-none border-l-4 border-l-primary",
  darkMode: false,
};
