// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Gola wala",
  category: "Ice cream shop",
  address: "\nGF-08, Atlantis one, opp. Hirashs arcade, nr. SAGAR SANGEET COMPLEX, Science City, Sola, Ahmedabad, Gujarat 380060",
  phone: "",
  email: "",
  website: "http://www.golawala.in/",
  mapUrl: "https://www.google.com/maps/place/Gola+wala/@23.0769843,72.518777,17z/data=!3m1!4b1!4m6!3m5!1s0x395e9d00319b07c9:0x39a301934cb8942f!8m2!3d23.0769843!4d72.518777!16s%2Fg%2F11ypr7ghnt?entry=ttu&g_ep=EgoyMDI2MDUyNS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0769843",
  longitude: "72.518777",
  rating: "",
  reviewsCount: "64",
  openingHours: "Show open hours for the week",
  logo: "/images/logo.png",
  images: ["/images/gmap_1779967934747_0.jpg", "/images/gmap_1779967935111_1.jpg", "/images/gmap_1779967935448_2.jpg", "/images/gmap_1779967935614_3.jpg", "/images/gmap_1779967935834_4.jpg", "/images/gmap_1779967936130_5.jpg", "/images/gmap_1779967936238_6.jpg", "/images/website_0.jpg"],
  description: "",
  socials: {"facebook":"https://www.facebook.com/golawalaofficial","instagram":"https://www.instagram.com/golawala_official/?igsh=Y3Nvc3N0OHA0NGFq","whatsapp":"https://api.whatsapp.com/send/?phone=919824318583&text&type=phone_number&app_absent=0"},
};

export const aiContent = {
  tagline: "Gola wala's Science City Delights",
  heroDescription: "Indulge in the coolest treats at Gola wala, located in the heart of Science City, Ahmedabad. Our ice cream shop offers a wide range of flavors to beat the heat. Visit us today at GF-08, Atlantis one, opp. Hirashs arcade, nr. SAGAR SANGEET COMPLEX, and taste the difference!",
  aboutTitle: "The Story of Gola wala",
  aboutText: "Located in the vibrant area of Science City, Ahmedabad, Gola wala has been a favorite among locals and visitors alike. Our address at  GF-08, Atlantis one, opp. Hirashs arcade, nr. SAGAR SANGEET COMPLEX, makes us easily accessible to all. We take pride in serving unique and delicious ice cream flavors that cater to all tastes. Our mission is to provide a refreshing experience to our customers, making us a must-visit destination in the city.",
  services: [
    { icon: "🍦", title: "Gola wala Special", description: "Our signature ice cream flavor, made with the finest ingredients and a touch of love" },
    { icon: "🌮", title: "Falooda", description: "A classic Indian dessert, crafted with creamy ice cream, vermicelli, and a hint of cardamom" },
    { icon: "🍦", title: "Kulfi", description: "Traditional Indian ice cream, made with milk, cream, and a blend of spices, served in a variety of flavors" },
    { icon: "🥤", title: "Milkshakes", description: "Thick, creamy, and indulgent, our milkshakes are the perfect treat to satisfy your cravings" },
    { icon: "🍭", title: "Sundaes", description: "A decadent combination of ice cream, toppings, and sauces, creating a delightful treat for your taste buds" },
    { icon: "🎂", title: "Ice Cream Cakes", description: "Customizable cakes, made with our signature ice cream, perfect for special occasions and celebrations" }
  ],
  whyChooseUs: [
    { icon: "👍", title: "Unique Flavors", description: "We offer a wide range of unique and delicious flavors, crafted with love and care to satisfy your taste buds" },
    { icon: "🏙️", title: "Prime Location", description: "Located in the heart of Science City, Ahmedabad, we are easily accessible to all, making us a perfect destination for a quick treat or a leisurely outing" },
    { icon: "👫", title: "Friendly Service", description: "Our staff is dedicated to providing exceptional customer service, ensuring that you have a wonderful experience at Gola wala" },
    { icon: "👌", title: "Quality Ingredients", description: "We use only the finest ingredients, sourced from trusted suppliers, to craft our delicious ice cream flavors" }
  ],
  testimonials: [
    { name: "Jaya Mehta", role: "Local Resident", text: "I've been a regular at Gola wala for years, and their ice cream never fails to impress. The Gola wala Special is my favorite!", rating: 5 },
    { name: "Jatin Shah", role: "Tourist", text: "I stumbled upon Gola wala while exploring Science City, and I'm so glad I did. Their Falooda is a must-try!", rating: 5 },
    { name: "Jaspreet Kaur", role: "Food Blogger", text: "Gola wala's unique flavors and friendly service make it a standout in the city. I highly recommend their Milkshakes!", rating: 5 }
  ],
  portfolio: { categories: [{ name: "Ice Cream Flavors", items: [{ title: "Gola wala Special", description: "Our signature ice cream flavor, made with the finest ingredients", icon: "🍦" }, { title: "Kulfi", description: "Traditional Indian ice cream, made with milk, cream, and a blend of spices", icon: "🍦" }, { title: "Falooda", description: "A classic Indian dessert, crafted with creamy ice cream, vermicelli, and a hint of cardamom", icon: "🌮" }] },
    { name: "Special Treats", items: [{ title: "Milkshakes", description: "Thick, creamy, and indulgent, our milkshakes are the perfect treat", icon: "🥤" }, { title: "Sundaes", description: "A decadent combination of ice cream, toppings, and sauces", icon: "🍭" }, { title: "Ice Cream Cakes", description: "Customizable cakes, made with our signature ice cream", icon: "🎂" }] },
    { name: "Seasonal Offers", items: [{ title: "Summer Specials", description: "Refreshing flavors and treats to beat the heat", icon: "☀️" }, { title: "Winter Delights", description: "Warm and comforting flavors to enjoy during the winter months", icon: "❄️" }, { title: "Festive Offers", description: "Special flavors and discounts during festive seasons", icon: "🎉" }] },
    { name: "Customer Favorites", items: [{ title: "Gola wala Special", description: "Our signature ice cream flavor, a customer favorite", icon: "🍦" }, { title: "Falooda", description: "A classic Indian dessert, loved by our customers", icon: "🌮" }, { title: "Kulfi", description: "Traditional Indian ice cream, a favorite among our patrons", icon: "🍦" }] }] },
  faq: { items: [{ question: "What are the business hours of Gola wala?", answer: "We are open from 11am to 11pm, 7 days a week. Please note that hours may vary during festive seasons or special events." },
    { question: "Do you offer customization options for ice cream cakes?", answer: "Yes, we offer customization options for ice cream cakes. Please contact us at least 24 hours in advance to place your order." },
    { question: "Can I purchase Gola wala merchandise online?", answer: "Currently, our merchandise is only available for purchase in-store. However, we are working on making it available online soon." },
    { question: "How do I get to Gola wala from the nearest metro station?", answer: "The nearest metro station is Science City. From there, take a short taxi ride or walk for about 10-15 minutes to reach our location at GF-08, Atlantis one, opp. Hirashs arcade, nr. SAGAR SANGEET COMPLEX." },
    { question: "Do you offer any discounts or promotions?", answer: "Yes, we offer various discounts and promotions throughout the year. Follow us on social media or sign up for our newsletter to stay updated on our latest offers." },
    { question: "Can I book a party or event at Gola wala?", answer: "Yes, we can accommodate parties and events. Please contact us at least 7 days in advance to discuss details and availability." }] },
  ctaTitle: "Indulge in the Coolest Treats",
  ctaDescription: "Visit us today and experience the unique flavors of Gola wala. We can't wait to serve you!",
  ctaButtonText: "Get Your Treat",
  metaDescription: "Gola wala: Ahmedabad's favorite ice cream shop",
};

export const siteConfig = {
  layout: "minimal-luxury",
  theme: "warm",
  sections: ["about", "customer", "a", "faq", "skip", "google", "alt", "gallery", "open", "blog", "structured", "contact", "portfolio"],
  heroVariant: "fullscreen-cinematic",
  navStyle: "sticky-blur",
  animationStyle: "blur-in-sharp",
  cardStyle: "rounded-none border-l-4 border-l-primary",
  darkMode: false,
};
