// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Gola wala",
  category: "Ice cream shop",
  address: "\nGF-08, Atlantis one, opp. Hirashs arcade, nr. SAGAR SANGEET COMPLEX, Science City, Sola, Ahmedabad, Gujarat 380060",
  phone: "",
  email: "",
  website: "http://www.golawala.in/",
  mapUrl: "https://www.google.com/maps/place/Gola+wala/@23.0769843,72.518777,17z/data=!3m1!4b1!4m6!3m5!1s0x395e9d00319b07c9:0x39a301934cb8942f!8m2!3d23.0769843!4d72.518777!16s%2Fg%2F11ypr7ghnt?entry=ttu&g_ep=EgoyMDI2MDUyNS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0769843",
  longitude: "72.518777",
  rating: "",
  reviewsCount: "64",
  openingHours: "Show open hours for the week",
  logo: "/images/logo.png",
  images: ["/images/gmap_1779966440993_0.jpg", "/images/gmap_1779966441322_1.jpg", "/images/gmap_1779966441626_2.jpg", "/images/gmap_1779966442090_3.jpg", "/images/gmap_1779966442356_4.jpg", "/images/gmap_1779966442770_5.jpg", "/images/gmap_1779966443017_6.jpg", "/images/website_0.jpg"],
  description: "",
  socials: {"facebook":"https://www.facebook.com/golawalaofficial","instagram":"https://www.instagram.com/golawala_official/?igsh=Y3Nvc3N0OHA0NGFq","whatsapp":"https://api.whatsapp.com/send/?phone=919824318583&text&type=phone_number&app_absent=0"},
};

export const aiContent = {
  tagline: "Gola wala's Science City Delights",
  heroDescription: "Experience the ultimate ice cream destination at Gola wala, located in the heart of Science City, Ahmedabad. Our unique flavors and refreshing treats will leave you wanting more. Visit us today at GF-08, Atlantis one, opp. Hirashs arcade, nr. SAGAR SANGEET COMPLEX!",
  aboutTitle: "The Story Behind Gola wala",
  aboutText: "Gola wala is nestled in the vibrant Science City area of Ahmedabad, at GF-08, Atlantis one, where the city's energy meets our passion for ice cream. Our shop is a must-visit destination for anyone looking to beat the heat with a cool treat. With a wide range of flavors to choose from, we cater to all taste buds. Our mission is to provide the highest quality ice cream and exceptional customer service to our valued customers.",
  services: [
    { icon: "🍦", title: "Gola wala Special", description: "Indulge in our signature ice cream flavor, made with the finest ingredients and a touch of love." },
    { icon: "🌴", title: "Summer Coolers", description: "Beat the heat with our refreshing summer coolers, perfect for hot days in Ahmedabad." },
    { icon: "👥", title: "Party Packs", description: "Make your party a success with our customizable party packs, filled with a variety of ice cream flavors." },
    { icon: "🎂", title: "Birthday Treats", description: "Celebrate your special day with our delicious birthday treats, designed to make your day even sweeter." },
    { icon: "👫", title: "Couple's Delight", description: "Enjoy a romantic treat with your loved one, featuring our unique couple's ice cream flavors." },
    { icon: "🏙️", title: "Science City Specials", description: "Experience the flavors of Science City with our special ice cream flavors, inspired by the city's vibrant culture." }
  ],
  whyChooseUs: [
    { icon: "💯", title: "Quality Guarantee", description: "We use only the finest ingredients to ensure our ice cream is of the highest quality." },
    { icon: "👨‍💼", title: "Exceptional Service", description: "Our friendly staff are dedicated to providing exceptional customer service, making your visit a memorable one." },
    { icon: "🌟", title: "Unique Flavors", description: "Our ice cream flavors are carefully crafted to provide a unique and delicious experience for our customers." },
    { icon: "👍", title: "Locally Loved", description: "We are proud to be a part of the Science City community, and our customers love us for our commitment to quality and service." }
  ],
  testimonials: [
    { name: "Palak Jain", role: "Regular Customer", text: "I've been visiting Gola wala for months now, and their ice cream never fails to impress. The Gola wala Special is my favorite!", rating: 5 },
    { name: "Pankaj Mehta", role: "Party Organizer", text: "Gola wala's party packs were a hit at my friend's birthday party. The variety of flavors and excellent service made the event a success.", rating: 5 },
    { name: "Prachi Shah", role: "Food Blogger", text: "As a food blogger, I've tried many ice cream shops in Ahmedabad, but Gola wala stands out for its unique flavors and exceptional service. The Summer Coolers are a must-try!", rating: 5 }
  ],
  portfolio: { categories: [{ name: "Ice Cream Flavors", items: [{ title: "Gola wala Special", description: "Our signature ice cream flavor", icon: "🍦" }, { title: "Mango Madness", description: "A sweet and tangy mango ice cream flavor", icon: "🥭" }, { title: "Chocolate Chip", description: "A classic chocolate ice cream flavor with a twist", icon: "🍫" }] },
    { name: "Cakes and Desserts", items: [{ title: "Ice Cream Cake", description: "A customizable ice cream cake for special occasions", icon: "🎂" }, { title: "Brownie Sundae", description: "A rich and decadent brownie sundae with ice cream", icon: "🍪" }, { title: "Fruit Salad", description: "A refreshing fruit salad with a scoop of ice cream", icon: "🍓" }] },
    { name: "Special Offers", items: [{ title: "Happy Hour", description: "Discounted ice cream prices during happy hour", icon: "🕰️" }, { title: "Loyalty Program", description: "Earn points for every purchase and redeem rewards", icon: "📈" }, { title: "Gift Vouchers", description: "Purchase gift vouchers for friends and family", icon: "🎁" }] },
    { name: "Events and Parties", items: [{ title: "Birthday Parties", description: "Host your child's birthday party at Gola wala", icon: "🎂" }, { title: "Corporate Events", description: "Customize ice cream packages for your corporate event", icon: "📊" }, { title: "Wedding Functions", description: "Make your wedding function a sweet success with Gola wala", icon: "💕" }] }] },
  faq: { items: [{ question: "What are the business hours of Gola wala?", answer: "Gola wala is open from 11am to 11pm, 7 days a week." },
    { question: "Do you offer customized ice cream flavors for parties?", answer: "Yes, we offer customized ice cream flavors for parties and events. Please contact us for more information." },
    { question: "Can I purchase gift vouchers at Gola wala?", answer: "Yes, you can purchase gift vouchers at Gola wala. They are available in various denominations and can be redeemed at our shop." },
    { question: "Do you have a loyalty program?", answer: "Yes, we have a loyalty program that rewards our regular customers with points for every purchase. These points can be redeemed for free ice cream and other rewards." },
    { question: "Can I place an order for delivery or takeout?", answer: "Yes, we offer delivery and takeout services. Please contact us for more information and to place your order." },
    { question: "How can I get in touch with Gola wala?", answer: "You can contact us through our website, email, or phone. We are always happy to hear from our customers and help with any queries." }] },
  ctaTitle: "Get Your Favorite Ice Cream Now",
  ctaDescription: "Visit us today and indulge in the best ice cream in Science City. Our friendly staff are waiting to serve you!",
  ctaButtonText: "Order Now",
  metaDescription: "Gola wala: Science City's favorite ice cream destination",
};

export const siteConfig = {
  layout: "minimal-luxury",
  theme: "warm",
  sections: ["about", "customer", "a", "faq", "skip", "google", "alt", "gallery", "open", "blog", "structured", "contact", "portfolio"],
  heroVariant: "fullscreen-cinematic",
  navStyle: "sticky-blur",
  animationStyle: "blur-in-sharp",
  cardStyle: "rounded-none border-l-4 border-l-primary",
  darkMode: false,
};
